// Generated by CoffeeScript 2.2.1
angular.module('ngApi', ['ngLocalStorage']).provider('$api', [
  function() {
    return {
      baseUri: '',
      init: function(uri) {
        return this.baseUri = uri.replace(/(\/)*$/i,
  '');
      },
      $get: function() {
        return {
          baseUri: this.baseUri
        };
      }
    };
  }
]).factory('baseUri', [
  '$api',
  function($api) {
    return $api.baseUri;
  }
]).factory('beforeRequest', [
  '$localStorage',
  'baseUri',
  function($db,
  uri) {
    return {
      request: function(config) {
        var token;
        token = $db.get('token');
        if (token && config.url.indexOf(uri) === 0) {
          config.headers['Authorization'] = token;
        }
        return config;
      }
    };
  }
]).config([
  '$httpProvider',
  function($httpProvider) {
    $httpProvider.defaults.useXDomain = true;
    $httpProvider.interceptors.push('beforeRequest');
  }
]);
